version: "3.8"
services:
  app:
    build: ./docker
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - ipfs
  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    ports:
      - "5001:5001"
      - "8080:8080"
