version: "3.8"
services:
  app:
    build: ./docker
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - ipfs
      - localstack
  ipfs:
    image: ipfs/kubo
    ports:
      - "4001:4001" # IPFSノード通信用
      - "5001:5001" # IPFS API用
      - "8080:8080" # HTTPゲートウェイ用
    volumes:
      - "./ipfs/staging:/export" # ステージングエリア用
      - "./ipfs/data:/data/ipfs" # IPFSデータ用
    command: ["daemon", "--migrate=true"] # データベースが古い場合は自動的にマイグレーションを行う
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
